package countryModel

type Model struct {
	BD string `json:"BD"`
	BE string `json:"BE"`
	BF string `json:"BF"`
	BG string `json:"BG"`
	BA string `json:"BA"`
	BB string `json:"BB"`
	WF string `json:"WF"`
	BL string `json:"BL"`
	BM string `json:"BM"`
	BN string `json:"BN"`
	BO string `json:"BO"`
	BH string `json:"BH"`
	BI string `json:"BI"`
	BJ string `json:"BJ"`
	BT string `json:"BT"`
	JM string `json:"JM"`
	BV string `json:"BV"`
	BW string `json:"BW"`
	WS string `json:"WS"`
	BQ string `json:"BQ"`
	BR string `json:"BR"`
	BS string `json:"BS"`
	JE string `json:"JE"`
	BY string `json:"BY"`
	BZ string `json:"BZ"`
	RU string `json:"RU"`
	RW string `json:"RW"`
	RS string `json:"RS"`
	TL string `json:"TL"`
	RE string `json:"RE"`
	TM string `json:"TM"`
	TJ string `json:"TJ"`
	RO string `json:"RO"`
	TK string `json:"TK"`
	GW string `json:"GW"`
	GU string `json:"GU"`
	GT string `json:"GT"`
	GS string `json:"GS"`
	GR string `json:"GR"`
	GQ string `json:"GQ"`
	GP string `json:"GP"`
	JP string `json:"JP"`
	GY string `json:"GY"`
	GG string `json:"GG"`
	GF string `json:"GF"`
	GE string `json:"GE"`
	GD string `json:"GD"`
	GB string `json:"GB"`
	GA string `json:"GA"`
	SV string `json:"SV"`
	GN string `json:"GN"`
	GM string `json:"GM"`
	GL string `json:"GL"`
	GI string `json:"GI"`
	GH string `json:"GH"`
	OM string `json:"OM"`
	TN string `json:"TN"`
	JO string `json:"JO"`
	HR string `json:"HR"`
	HT string `json:"HT"`
	HU string `json:"HU"`
	HK string `json:"HK"`
	HN string `json:"HN"`
	HM string `json:"HM"`
	VE string `json:"VE"`
	PR string `json:"PR"`
	PS string `json:"PS"`
	PW string `json:"PW"`
	PT string `json:"PT"`
	SJ string `json:"SJ"`
	PY string `json:"PY"`
	IQ string `json:"IQ"`
	PA string `json:"PA"`
	PF string `json:"PF"`
	PG string `json:"PG"`
	PE string `json:"PE"`
	PK string `json:"PK"`
	PH string `json:"PH"`
	PN string `json:"PN"`
	PL string `json:"PL"`
	PM string `json:"PM"`
	ZM string `json:"ZM"`
	EH string `json:"EH"`
	EE string `json:"EE"`
	EG string `json:"EG"`
	ZA string `json:"ZA"`
	EC string `json:"EC"`
	IT string `json:"IT"`
	VN string `json:"VN"`
	SB string `json:"SB"`
	ET string `json:"ET"`
	SO string `json:"SO"`
	ZW string `json:"ZW"`
	SA string `json:"SA"`
	ES string `json:"ES"`
	ER string `json:"ER"`
	ME string `json:"ME"`
	MD string `json:"MD"`
	MG string `json:"MG"`
	MF string `json:"MF"`
	MA string `json:"MA"`
	MC string `json:"MC"`
	UZ string `json:"UZ"`
	MM string `json:"MM"`
	ML string `json:"ML"`
	MO string `json:"MO"`
	MN string `json:"MN"`
	MH string `json:"MH"`
	MK string `json:"MK"`
	MU string `json:"MU"`
	MT string `json:"MT"`
	MW string `json:"MW"`
	MV string `json:"MV"`
	MQ string `json:"MQ"`
	MP string `json:"MP"`
	MS string `json:"MS"`
	MR string `json:"MR"`
	IM string `json:"IM"`
	UG string `json:"UG"`
	TZ string `json:"TZ"`
	MY string `json:"MY"`
	MX string `json:"MX"`
	IL string `json:"IL"`
	FR string `json:"FR"`
	IO string `json:"IO"`
	SH string `json:"SH"`
	FI string `json:"FI"`
	FJ string `json:"FJ"`
	FK string `json:"FK"`
	FM string `json:"FM"`
	FO string `json:"FO"`
	NI string `json:"NI"`
	NL string `json:"NL"`
	NO string `json:"NO"`
	NA string `json:"NA"`
	VU string `json:"VU"`
	NC string `json:"NC"`
	NE string `json:"NE"`
	NF string `json:"NF"`
	NG string `json:"NG"`
	NZ string `json:"NZ"`
	NP string `json:"NP"`
	NR string `json:"NR"`
	NU string `json:"NU"`
	CK string `json:"CK"`
	XK string `json:"XK"`
	CI string `json:"CI"`
	CH string `json:"CH"`
	CO string `json:"CO"`
	CN string `json:"CN"`
	CM string `json:"CM"`
	CL string `json:"CL"`
	CC string `json:"CC"`
	CA string `json:"CA"`
	CG string `json:"CG"`
	CF string `json:"CF"`
	CD string `json:"CD"`
	CZ string `json:"CZ"`
	CY string `json:"CY"`
	CX string `json:"CX"`
	CR string `json:"CR"`
	CW string `json:"CW"`
	CV string `json:"CV"`
	CU string `json:"CU"`
	SZ string `json:"SZ"`
	SY string `json:"SY"`
	SX string `json:"SX"`
	KG string `json:"KG"`
	KE string `json:"KE"`
	SS string `json:"SS"`
	SR string `json:"SR"`
	KI string `json:"KI"`
	KH string `json:"KH"`
	KN string `json:"KN"`
	KM string `json:"KM"`
	ST string `json:"ST"`
	SK string `json:"SK"`
	KR string `json:"KR"`
	SI string `json:"SI"`
	KP string `json:"KP"`
	KW string `json:"KW"`
	SN string `json:"SN"`
	SM string `json:"SM"`
	SL string `json:"SL"`
	SC string `json:"SC"`
	KZ string `json:"KZ"`
	KY string `json:"KY"`
	SG string `json:"SG"`
	SE string `json:"SE"`
	SD string `json:"SD"`
	DO string `json:"DO"`
	DM string `json:"DM"`
	DJ string `json:"DJ"`
	DK string `json:"DK"`
	VG string `json:"VG"`
	DE string `json:"DE"`
	YE string `json:"YE"`
	DZ string `json:"DZ"`
	US string `json:"US"`
	UY string `json:"UY"`
	YT string `json:"YT"`
	UM string `json:"UM"`
	LB string `json:"LB"`
	LC string `json:"LC"`
	LA string `json:"LA"`
	TV string `json:"TV"`
	TW string `json:"TW"`
	TT string `json:"TT"`
	TR string `json:"TR"`
	LK string `json:"LK"`
	LI string `json:"LI"`
	LV string `json:"LV"`
	TO string `json:"TO"`
	LT string `json:"LT"`
	LU string `json:"LU"`
	LR string `json:"LR"`
	LS string `json:"LS"`
	TH string `json:"TH"`
	TF string `json:"TF"`
	TG string `json:"TG"`
	TD string `json:"TD"`
	TC string `json:"TC"`
	LY string `json:"LY"`
	VA string `json:"VA"`
	VC string `json:"VC"`
	AE string `json:"AE"`
	AD string `json:"AD"`
	AG string `json:"AG"`
	AF string `json:"AF"`
	AI string `json:"AI"`
	VI string `json:"VI"`
	IS string `json:"IS"`
	IR string `json:"IR"`
	AM string `json:"AM"`
	AL string `json:"AL"`
	AO string `json:"AO"`
	AQ string `json:"AQ"`
	AS string `json:"AS"`
	AR string `json:"AR"`
	AU string `json:"AU"`
	AT string `json:"AT"`
	AW string `json:"AW"`
	IN string `json:"IN"`
	AX string `json:"AX"`
	AZ string `json:"AZ"`
	IE string `json:"IE"`
	ID string `json:"ID"`
	UA string `json:"UA"`
	QA string `json:"QA"`
	MZ string `json:"MZ"`
}
